analyzer:
  strong-mode: true
  errors:
    unused_local_variable: error
    invalid_assignment: error
    assignment_to_const: error
    assignment_to_final: error
    missing_return: error
    not_enough_required_arguments: error
    undefined_function: error
    undefined_method: error
    undefined_class: error
linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - comment_references
    - control_flow_in_finally
    - hash_and_equals
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
    - unrelated_type_equality_checks
